# Sniperkit-Bot
# - Status: analyzed

fixtures:
  symlinks:
    fluent_bit: "#{source_dir}"
    kubernetes: "#{source_dir}/../kubernetes"
    concat: "#{source_dir}/../concat"
    stdlib: "#{source_dir}/../stdlib"
    aws_es_proxy: "#{source_dir}/../aws_es_proxy"
